-- =============================================================================
-- 0004 — Blog: categories, posts (draft → published), image storage.
--
-- Run once in Supabase → SQL Editor (after 0001–0003). Safe to re-run.
--
-- Any admin can write, publish and edit posts. Editing a PUBLISHED post never
-- changes the live version directly: edits autosave into `pending`, and only
-- "Update post" copies them into the live columns (the site build reads the
-- live columns only). "Discard changes" just clears `pending`.
--
-- The public (anon key, used by the site build) reads published posts only.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Categories
-- -----------------------------------------------------------------------------
create table if not exists public.categories (
    id         smallint generated by default as identity primary key,
    slug       text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) <= 60),
    name       text not null check (char_length(name) between 1 and 60),
    sort_order int not null default 0,
    created_at timestamptz not null default now()
);

insert into public.categories (slug, name, sort_order) values
    ('tips-strategi',   'Tips & Strategi',            10),
    ('studi-kasus',     'Studi Kasus (Case Studies)', 20),
    ('fnb-cafe',        'F&B & Cafe',                 30),
    ('otomotif',        'Otomotif',                   40),
    ('branding-desain', 'Branding & Desain',          50),
    ('kabar-kreassi',   'Kabar Kreassi',              60)
on conflict (slug) do nothing;

alter table public.categories enable row level security;
revoke all on public.categories from anon, authenticated;
grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;

drop policy if exists "categories: everyone reads" on public.categories;
create policy "categories: everyone reads" on public.categories for select to anon, authenticated using (true);
drop policy if exists "categories: admins manage" on public.categories;
create policy "categories: admins manage" on public.categories for all to authenticated
    using ((select public.is_admin())) with check ((select public.is_admin()));

-- -----------------------------------------------------------------------------
-- Posts
-- -----------------------------------------------------------------------------
create table if not exists public.posts (
    id            uuid primary key default gen_random_uuid(),
    title         text not null default '' check (char_length(title) <= 200),
    slug          text unique check (slug is null or (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) <= 100)),
    lang          text not null default 'id' check (lang in ('id', 'en')),
    category_id   smallint references public.categories (id) on delete set null,
    excerpt       text check (char_length(excerpt) <= 300),        -- also the Google description
    focus_keyword text check (char_length(focus_keyword) <= 80),   -- for the SEO checklist only
    cover_path    text check (char_length(cover_path) <= 300),     -- path in the blog-images bucket
    cover_alt     text check (char_length(cover_alt) <= 200),
    content       jsonb not null default '{"type": "doc", "content": []}'::jsonb
                  check (pg_column_size(content) <= 500000),
    status        text not null default 'draft' check (status in ('draft', 'published')),
    pending       jsonb check (pending is null or pg_column_size(pending) <= 520000), -- unpublished edits to a live post
    author_id     uuid references auth.users (id) on delete set null,
    updated_by    uuid references auth.users (id) on delete set null,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    published_at  timestamptz,
    constraint posts_publishable check (status <> 'published' or (slug is not null and char_length(title) > 0))
);

create index if not exists posts_status_updated_idx on public.posts (status, updated_at desc);

-- Bookkeeping for every write, whoever makes it.
create or replace function public.posts_bookkeeping()
returns trigger
language plpgsql security definer
set search_path = ''
as $$
begin
    new.updated_at := now();
    new.updated_by := coalesce(auth.uid(), new.updated_by);
    if tg_op = 'INSERT' then
        new.created_at := now();
        new.author_id  := coalesce(auth.uid(), new.author_id);
    else
        new.created_at := old.created_at;
        new.author_id  := old.author_id; -- who created it never changes
    end if;
    if new.status = 'published' then
        -- Keep the original publish date when a post is unpublished and published again.
        new.published_at := coalesce(case when tg_op = 'UPDATE' then old.published_at end, new.published_at, now());
    else
        new.pending := null; -- drafts are edited directly; nothing is pending
    end if;
    return new;
end;
$$;

drop trigger if exists posts_bookkeeping on public.posts;
create trigger posts_bookkeeping before insert or update on public.posts
    for each row execute function public.posts_bookkeeping();

alter table public.posts enable row level security;
revoke all on public.posts from anon, authenticated;
grant select (id, title, slug, lang, category_id, excerpt, cover_path, cover_alt, content, status, created_at, updated_at, published_at)
    on public.posts to anon;
grant select, insert, update, delete on public.posts to authenticated;

drop policy if exists "posts: public reads published" on public.posts;
create policy "posts: public reads published" on public.posts for select to anon
    using (status = 'published');

drop policy if exists "posts: admins full access" on public.posts;
create policy "posts: admins full access" on public.posts for all to authenticated
    using ((select public.is_admin())) with check ((select public.is_admin()));

-- -----------------------------------------------------------------------------
-- Image storage: public to read (the site shows them), admins upload/replace.
-- -----------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('blog-images', 'blog-images', true, 5242880, array['image/webp', 'image/jpeg', 'image/png', 'image/gif'])
on conflict (id) do update set public = excluded.public,
    file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "blog images: admins upload" on storage.objects;
create policy "blog images: admins upload" on storage.objects for insert to authenticated
    with check (bucket_id = 'blog-images' and (select public.is_admin()));

drop policy if exists "blog images: admins update" on storage.objects;
create policy "blog images: admins update" on storage.objects for update to authenticated
    using (bucket_id = 'blog-images' and (select public.is_admin()))
    with check (bucket_id = 'blog-images' and (select public.is_admin()));

drop policy if exists "blog images: admins delete" on storage.objects;
create policy "blog images: admins delete" on storage.objects for delete to authenticated
    using (bucket_id = 'blog-images' and (select public.is_admin()));
